<x-layout title="Başiskele Çiçek | Başiskele ve çevresine çiçek siparişi" description="Başiskele ve çevresine çiçek siparişi için buketler, güller, aranjmanlar ve saksı çiçekleri.">
    <section class="relative isolate overflow-hidden bg-linear-to-br from-rose via-gold to-forest-dark px-4 py-16 text-cream sm:px-6 sm:py-24 lg:px-8"><div class="absolute -left-20 top-0 size-72 rounded-full bg-rose-soft/25 blur-3xl"></div><div class="absolute -right-16 bottom-0 size-80 rounded-full bg-lavender/20 blur-3xl"></div><div class="relative mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p class="text-sm font-bold tracking-[0.2em] text-rose-soft uppercase">Başiskele’nin çiçek durağı</p><h1 class="mt-4 max-w-2xl font-display text-5xl font-bold leading-[1.02] sm:text-6xl">Başiskele ve çevresine <span class="text-rose-soft">çiçek siparişi</span></h1><p class="mt-6 max-w-xl text-base leading-7 text-cream/85 sm:text-lg">İçten bir tebessüm bırakmak için seçilmiş taze çiçekler, zarif buketler ve özenle hazırlanan aranjmanlar.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('products.index') }}" class="inline-flex min-h-12 items-center rounded-full bg-white px-6 font-bold text-forest shadow-lg transition hover:-translate-y-0.5 hover:bg-rose-soft">Çiçekleri keşfet</a><a href="#iletisim" class="inline-flex min-h-12 items-center rounded-full border border-cream/45 px-6 font-bold text-cream transition hover:bg-cream/10">İletişime geç</a></div></div><div class="relative mx-auto w-full max-w-md"><div class="absolute -inset-5 rounded-[3rem] border border-cream/25"></div><img src="{{ asset('images/placeholders/buketler.svg') }}" alt="Başiskele Çiçek buket illüstrasyonu" class="relative w-full rounded-[2.5rem] bg-rose-soft shadow-2xl"><div class="absolute -bottom-5 -left-3 rounded-2xl bg-white px-4 py-3 text-sm font-bold text-forest shadow-lg">Taze çiçeklerle<br>hazırlanır</div></div></div></section>

    <section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div class="flex items-end justify-between gap-5"><div><p class="text-sm font-bold tracking-[0.18em] text-gold uppercase">Kategoriler</p><h2 class="mt-2 font-display text-4xl font-bold text-forest">Her ana uygun bir çiçek</h2></div><a href="{{ route('products.index') }}" class="hidden text-sm font-bold text-forest underline decoration-gold underline-offset-4 sm:block">Tümünü görüntüle</a></div><div class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach ($categories as $category)<x-category-card :category="$category" />@endforeach</div></section>

    <section class="bg-cream-deep px-4 py-16 sm:px-6 lg:px-8"><div class="mx-auto max-w-7xl"><div class="flex items-end justify-between gap-5"><div><p class="text-sm font-bold tracking-[0.18em] text-gold uppercase">Öne çıkanlar</p><h2 class="mt-2 font-display text-4xl font-bold text-forest">Bugün en çok sevilenler</h2></div><a href="{{ route('products.index') }}" class="hidden text-sm font-bold text-forest underline decoration-gold underline-offset-4 sm:block">Tüm çiçekleri gör</a></div><div class="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">@foreach ($featuredProducts as $product)<x-product-card :product="$product" />@endforeach</div></div></section>

    <section class="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><div class="rounded-[2rem] bg-rose-soft p-8 sm:p-10"><p class="text-sm font-bold tracking-[0.18em] text-rose uppercase">Bizden bir not</p><h2 class="mt-3 font-display text-4xl font-bold text-forest">Küçük anları güzelleştiriyoruz.</h2><p class="mt-5 max-w-xl leading-7 text-ink/75">Başiskele Çiçek, sevdiklerinize duygunuzu anlatmanın en doğal yolunu bulmanız için taze çiçekleri özenle bir araya getirir. Siparişinizi WhatsApp üzerinden kolayca konuşabiliriz.</p></div><div id="iletisim" class="rounded-[2rem] bg-forest p-8 text-cream sm:p-10"><p class="text-sm font-bold tracking-[0.18em] text-gold uppercase">WhatsApp siparişi</p><h2 class="mt-3 font-display text-4xl font-bold">Bize ne hazırlayacağınızı söyleyin.</h2><p class="mt-5 leading-7 text-cream/75">Ürün, renk ve mesaj tercihinizi paylaşın; size en uygun seçeneği birlikte netleştirelim.</p><div class="mt-7"><x-whats-app-button label="WhatsApp’tan mesaj gönder" /></div></div></section>

    <section class="border-t border-forest/10 bg-white px-4 py-12 sm:px-6 lg:px-8"><div class="mx-auto grid max-w-7xl gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p class="text-sm font-bold tracking-[0.18em] text-gold uppercase">Adres</p><h2 class="mt-2 font-display text-3xl font-bold text-forest">{{ config('store.address') }}</h2></div><a href="{{ config('store.map_url') }}" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-12 items-center justify-center rounded-full border border-forest/20 px-6 font-bold text-forest transition hover:bg-forest hover:text-cream">Haritada aç</a></div></section>

    @php($structuredData = ['@context' => 'https://schema.org', '@type' => 'Florist', 'name' => $store->name, 'url' => url('/'), 'telephone' => $store->phone, 'address' => ['@type' => 'PostalAddress', 'streetAddress' => $store->address, 'addressLocality' => 'Başiskele', 'addressRegion' => 'Kocaeli', 'addressCountry' => 'TR']])
    <script type="application/ld+json">@json($structuredData)</script>
</x-layout>
